// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vosxlftdamqzgzkgiotm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvc3hsZnRkYW1xemd6a2dpb3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjU3MDMsImV4cCI6MjA2MTcwMTcwM30.Sej865Zc6dSIaZDJxI_VI6k675AiBS442uIzP9VVNG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);